config/routes.rb
Rails.application.routes.draw do

  root 'stores#index'
  
  resources :stores, only: [:index, :new, :show, :create]
  resources :pets

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :store
  validates :name, :breed, :gender, presence: true
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :pets
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController


  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(name: params[:name], breed: params[:breed], gender: params[:gender])
    #@pet.store_id = 
    @pet.save
    redirect_to stores_path
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController


  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
    @pet = Pet.new
    @pet.store_id = @store.id
  end

  def new
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pets/new.html.erb
<h1>Add a new pet</h1>

<%= form_for [@store, @pet] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= f.label :breed %>
  <%= f.text_field :breed %><br />
  <%= f.label :gender %>
  <%= f.text_field :gender %><br />
  <% f.hidden_field :store_id %>
  <%= f.submit %>
<% end %>

app/views/stores/index.html.erb
<h1>Stores</h1>



<% @stores.each do |store| %>
  <ul>
    <li>
      <%= store.name %> 
    </li>
  </ul>
<% end %>

app/views/stores/show.html.erb
<h1>show view</h1>


<%= @store.name %>
<%= @store.pets do |pet| %>
  <%= pet.name %>
  <%= pet.breed %>
<% end  %>
<%= link_to 'Add new pet', new_pet_path(store_id: @store.id) %>